apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "form-submission-validation.fullname" . }}
  labels:
    {{- include "form-submission-validation.labels" . | nindent 4 }}
spec:
  {{- if not .Values.global.registry.formSubmissionValidation.hpa.enabled }}
  replicas: {{ .Values.global.registry.formSubmissionValidation.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "form-submission-validation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.global.registry.formSubmissionValidation.istio.sidecar.enabled }}
      annotations:
        {{- if .Values.global.registry.formSubmissionValidation.istio.sidecar.enabled }}
        sidecar.istio.io/inject: "true"
        {{- if .Values.global.istio.sidecar.requestsLimitsEnabled }}
        {{- include "formSubmissionValidation.istioResources" . | nindent 8 }}
        {{- else }}
        inject.istio.io/templates: 'sidecar,emptyRequestsLimits'
        {{- end }}
        {{- end }}
      {{- end }}
      labels:
        collect.logs: "plain-text"
        {{- include "form-submission-validation.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "form-submission-validation.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          env:
            {{- range $name, $value := .Values.global.registry.formSubmissionValidation.container.envVars }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            - name: LANGUAGE
              value: {{ .Values.global.language }}
            - name: FORM_PROVIDER_BASE_URL
              value: {{ .Values.environmentJs.formSchemaProviderUrl }}
            - name: DATA_FACTORY_BASE_URL
              value: {{ .Values.environmentJs.dataFactoryUrl }}
          {{- if .Values.global.container.requestsLimitsEnabled }}
          resources:
            {{- toYaml .Values.global.registry.formSubmissionValidation.container.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: form-submission-validation-environment-js
              mountPath: /app/environment.js
              subPath: environment.js
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: form-submission-validation-environment-js
          configMap:
            name: form-submission-validation-environment-js
