{{- if .Values.global.registry.formSubmissionValidation.hpa.enabled }}
apiVersion: {{ include "horizontalPodAutoscaler.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "form-submission-validation.fullname" . }}
  labels:
    {{- include "form-submission-validation.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "form-submission-validation.fullname" . }}
  minReplicas: {{ .Values.global.registry.formSubmissionValidation.hpa.minReplicas }}
  maxReplicas: {{ .Values.global.registry.formSubmissionValidation.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
{{- end }}
